apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: mongodb-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "MongoDB"
  labels:
    camel.apache.org/kamelet.type: "source"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "MongoDB Source"
    description: |-
      Consume documents from MongoDB.

      If the persistentTailTracking option will be enabled, the consumer will keep track of the last consumed message and on the next restart, the consumption will restart from that message. In case of persistentTailTracking enabled, the tailTrackIncreasingField must be provided (by default it is optional).

      If the persistentTailTracking option won't be enabled, the consumer will consume the whole collection and wait in idle for new documents to consume.
    required:
      - hosts
      - collection
      - password
      - username
      - database
    type: object
    properties:
      hosts:
        title: MongoDB Hosts
        description: Comma separated list of MongoDB Host Addresses in host:port format.
        type: string
      collection:
        title: MongoDB Collection
        description: Sets the name of the MongoDB collection to bind to this endpoint.
        type: string
      password:
        title: MongoDB Password
        description: User password for accessing MongoDB.
        type: string
        format: password
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
      username:
        title: MongoDB Username
        description: Username for accessing MongoDB.
        type: string
      database:
        title: MongoDB Database
        description: Sets the name of the MongoDB database to target.
        type: string
      persistentTailTracking:
        title: MongoDB Persistent Tail Tracking
        description: Enable persistent tail tracking, which is a mechanism to keep track of the last consumed message across system restarts. The next time the system is up, the endpoint will recover the cursor from the point where it last stopped slurping records.
        type: boolean
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:checkbox'
        default: false
      tailTrackIncreasingField:
        title: MongoDB Tail Track Increasing Field
        description: Correlation field in the incoming record which is of increasing nature and will be used to position the tailing cursor every time it is generated. 
        type: string
  dependencies:
    - "camel:kamelet"
    - "camel:mongodb"
    - "camel:jackson"
  flow:
    beans:
      - name: local-mongodb
        type: "#class:org.apache.camel.component.mongodb.MongoDbComponent"
    from:
      uri: "{{local-mongodb}}:test"
      parameters:
        hosts: "{{hosts}}"
        collection: "{{collection}}"
        password: "{{password}}"
        username: "{{username}}"
        database: "{{database}}"
        persistentTailTracking: "{{persistentTailTracking}}"
        tailTrackIncreasingField: "{{?tailTrackIncreasingField}}"
      steps:
      - marshal:
          json: {}
      - to: kamelet:sink
